#!/bin/sh
#
# "gjm" from xcolors.net
#

# special
foreground="#c5c5c5"
background="#1c1c1c"

# cursor
cursor="#c5c5c5"
invcursor="#1c1c1c"

# other
selbg="#1c1c1c"
selfg="#ea0054"
# black
color0="#1c1c1c"
color8="#666666"

# red
color1="#ea0054"
color9="#e41c99"

# green
color2="#bcce22"
color10="#b2db0f"

# yellow
color3="#e3ca32"
color11="#ff9f00"

# blue
color4="#048ac7"
color12="#40b1e4"

# magenta
color5="#833c9f"
color13="#be67e1"

# cyan
color6="#0ac1cd"
color14="#5dd8e1"

# white
color7="#e5e5e5"
color15="#f3f3f3"
