#!/bin/bash
#
# Volume script for dwmblocks

volume="$(pamixer --get-volume)"

status="$(pamixer --get-mute)"


#if [ "$volume" -lt "33" ] ; then
    #icon="[VOL_]"
    #[ "$volume" -lt "10" ] && icon="[MUTE]" && volume="0$volume"
#elif [ "$volume" -lt "66" ]; then
    #icon="[VOL-]"
#else
    #icon="[VOL^]"
#fi
#
#if [ "$volume" -gt "99" ] ; then
    #volume="99"
#fi

[ "$volume" -lt "66" ] && icon="VOL-" || icon="VOL^"
[ "$volume" -lt "33" ] && icon="VOL_"
[ "$volume" -lt "10" ] && volume=" $volume"
[ "$volume" -eq "0" ] && icon="MUTE"
[ "$volume" -gt "99" ] && volume=99
[ "$status" = true ] && icon="MUTE"

printf '%s %s' "$icon" "$volume"
#echo "$icon $volume%"
