#!/bin/bash
#
# Wifi status script for dwmblocks
#

status=$(iwctl station wlan0 show | grep 'State' | sed -e 's/ //g;s/State//g')
network=$(iwctl station wlan0 show | grep 'Connected network' | \
    sed -e 's/ //g;s/Connectednetwork//g')

case $status in
    "connected") status="WIFI " ;;
    "disconnected") status="DISC" ;;
    *) status="$(echo "$status" | cut -c -4 | tr "[:lower:]" "[:upper:]") " ;;
esac

printf '%s%s' "$status" "$network"
