#!/bin/sh
#
# Battery level notification daemon


# Low battery notification threshold
battlow=20
battcritical=15

# Full battery notification threshold
battfull=80

# Checking interval
interval=2

# set initial values
oldstatus=101
oldcapacity="a"

while : ; do
    capacity=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)
    if [ "$status" != "$oldstatus" ] || [ "$capacity" != "$oldcapacity" ] ; then

        case $status in
            Discharging)
                if [ "$capacity" -le $battcritical ] ; then
                    notify-send "Critically low battery" \
                        "Only $capacity% of battery left"
                elif [ "$capacity" -le $battlow ] ; then
                    notify-send --urgency=critical "Low battery" \
                        "Only $capacity% of battery left!"
                fi
            ;;
            Charging)
                [ "$capacity" -ge $battfull ] && \
                notify-send "Battery full" "Disconnect from charger"
        esac

        oldstatus=$status
        oldcapacity=$capacity

        kill -41 "$(pidof dwmblocks)"
    fi
    sleep $interval
done
