#!/bin/sh
#
# Battery level notification daemon


# Low battery notification threshold
battlow=20
battcritical=15

# Full battery notification threshold
battfull=80

# Checking interval
interval=2

# set initial values
oldstatus=101
oldcapacity="a"

while : ; do
    capacity=$(cat /sys/class/power_supply/BAT0/capacity)
    status=$(cat /sys/class/power_supply/BAT0/status)
    if [ $status != $oldstatus ] || [ $capacity != $oldcapacity ] ; then

        case $status in
            Discharging)
                [ $capacity -le $battcritical ] && \
                notify-send "Critically low battery" \
                  "Only $capacity% of battery left" || \
                [ $capacity -le $battlow ] && \
                notify-send "Low battery" "Only $capacity% of battery left"
            ;;
            Charging)
                [ $capacity -ge $battfull ] && \
                notify-send "Battery full" "Disconnect from charger"
        esac

        oldstatus=$status
        oldcapacity=$capacity

        kill -41 $(pidof dwmblocks)
    fi
    sleep $interval
done
