#!/bin/sh
#
# Dark Period mode can be toggled, and does 3 things when active:
# [ ] sets color temperature to the lowest setting using xsct if it's installed,
#     falling back to scp if it's not
# [ ] sets the picom shader to grayscale to improve legibility and contrast
# [ ] sets the current wallpaper to greyscale
#
# In order to make this script work you'll need:
#     picom
#     sct or xsct
#     feh
#     a couple of my other scripts:
#         temperature
#         background
#

usage() {
cat << EOF
Usage: ${0##*/} [options]
Options:
    -c  toggle compositor greyscale only
    -t  toggle screen temperature only
    -b  toggle greyscale background only
EOF
}

toggle_comp() {
if pgrep -a -x picom | grep glx-fshader-win > /dev/null ; then
    pkill -x picom
    sleep 1
    picom -b
    mode="color"
else
    pkill -x picom
    sleep 1
    shader="uniform sampler2D tex; uniform float opacity; void main() { vec4 c = texture2D(tex, gl_TexCoord[0].xy); float y = dot(c.rgb, vec3(0.2126, 0.7152, 0.0722)); gl_FragColor = opacity*vec4(y, y, y, c.a); }"
    picom -b --backend glx --glx-fshader-win "${shader}" 2> /dev/null
    mode="grayscale"
fi
}

case ${1#-} in
    h)
        usage
        exit 0
        ;;
    c)
        toggle_comp
        ;;
    b)
        toggle_bg
        ;;
    t)
        toggle_temp
        ;;
esac



