#!/bin/sh
#
# Dark Period mode can be toggled, and does 3 things when active:
# [ ] sets color temperature to the lowest setting using xsct if it's installed,
#     falling back to scp if it's not
# [ ] sets the picom shader to grayscale to improve legibility and contrast
# [ ] sets the current wallpaper to greyscale
#
# In order to make this script work you'll need:
#     picom
#     sct or xsct
#     feh
#     a couple of my other scripts:
#         temperature
#         background
#

usage() {
cat << EOF
Usage: ${0##*/} [OPTION]
Options:
    -h  help            display this help message
    -a  activate        activate dark period mode: low temperature and grayscale
    -d  deactivate      turn dark period mode off setting everything to default
    -c  compositor      toggle compositor greyscale only
    -t  temperature     toggle screen temperature only
    -b  background      toggle greyscale background only
EOF
}

color_comp() {
    pkill -x picom
    sleep 1
    picom -b
    # mode="color"
}

grayscale_comp() {
    pkill -x picom
    sleep 1
    shader="uniform sampler2D tex; uniform float opacity; void main() { vec4 c = texture2D(tex, gl_TexCoord[0].xy); float y = dot(c.rgb, vec3(0.2126, 0.7152, 0.0722)); gl_FragColor = opacity*vec4(y, y, y, c.a); }"
    picom -b --backend glx --glx-fshader-win "${shader}" 2> /dev/null
    # mode="grayscale"
}

toggle_comp() {
if pgrep -a -x picom | grep glx-fshader-win > /dev/null ; then
    color_comp
else
    grayscale_comp
fi
}

toggle_temp() {
    [ $(temperature -p) -ge 1100 ] && temperature -s 700 || temperature
}

case ${1#-} in
    h)
        usage
        exit 0
        ;;
    c)
        toggle_comp
        ;;
    b)
        # toggle_bg
        ;;
    t)
        toggle_temp
        ;;
    a)
      # if temperature is high set it to lowest value
        [ $(temperature -p) -ge 1100 ] && temperature -s 700

      # if compositor is grayscale don't set it to grayscale again
        if ! pgrep -a -x picom | grep glx-fshader-win > /dev/null ; then
        grayscale_comp
        fi

      # if background is colored set it to grayscale
        ;;
    d)
      # if temperature is low set it to default value
        [ $(temperature -p) -lt 1100 ] && temperature

      # if compositor is grayscale set it to default colors
        if pgrep -a -x picom | grep glx-fshader-win > /dev/null ; then
        color_comp
        fi

      # if background is grayscale set it to normal background
esac



