#!/bin/sh

usage() {
cat << EOF
Usage: ${0##*/} [OPTION]
Options:
    -h  help            display this help message
    -v  view            view note without editing and entering lines with time
EOF
}

diarydir="$HOME/vimwiki/diary"
filename="$diarydir/$(date +%Y-%m-%d).wiki"

if [ ! -f $filename ]; then
    printf '# Notes for %s\n\n' "$(date +%Y-%m-%d)" > $filename
    lastfile=$(ls $diarydir | tail -n 2 | head -n 1)
    printf 'Last note: [[%s]]\n' "$(basename $lastfile .wiki)" >> $filename
fi

printf '\n\n## %s\n\n' "$(date +%H:%M)" >> $filename

vim -c "norm Go" -c "startinsert" $filename
